//@GeneratedCode
namespace QTSchool.WebApi.Controllers.App
{
    ///
    /// Generated by the generator
    ///
    public sealed partial class StudentsController : Controllers.GenericController<QTSchool.Logic.Models.App.Student, QTSchool.WebApi.Models.App.StudentEdit, QTSchool.WebApi.Models.App.Student>
    {
        ///
        /// Generated by the generator
        ///
        static StudentsController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public StudentsController(QTSchool.Logic.Contracts.App.IStudentsAccess other)
        : base(other)
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        protected override QTSchool.WebApi.Models.App.Student ToOutModel(QTSchool.Logic.Models.App.Student accessModel)
        {
            var handled = false;
            var result = default(QTSchool.WebApi.Models.App.Student);
            BeforeToOutModel(accessModel, ref result, ref handled);
            if (handled == false || result == null)
            {
                result = QTSchool.WebApi.Models.App.Student.Create(accessModel);
            }
            AfterToOutModel(result);
            return result;
        }
        partial void BeforeToOutModel(QTSchool.Logic.Models.App.Student accessModel, ref QTSchool.WebApi.Models.App.Student? outModel, ref bool handled);
        partial void AfterToOutModel(QTSchool.WebApi.Models.App.Student outModel);
    }
}
