//@GeneratedCode
namespace QTSchool.Logic.DataContext
{
    ///
    /// Generated by the generator
    ///
    partial class ProjectDbContext
    {
        ///
        /// Generated by the generator
        ///
        public DbSet<Entities.App.Course>? CourseSet{ get; set; }
        ///
        /// Generated by the generator
        ///
        public DbSet<Entities.App.Student>? StudentSet{ get; set; }
        
        ///
        /// Generated by the generator
        ///
        partial void GetGeneratorDbSet<E>(ref DbSet<E>? dbSet, ref bool handled) where E : Entities.EntityObject
        {
            if (typeof(E) == typeof(Entities.App.Course))
            {
                dbSet = CourseSet as DbSet<E>;
                handled = true;
            }
            else if (typeof(E) == typeof(Entities.App.Student))
            {
                dbSet = StudentSet as DbSet<E>;
                handled = true;
            }
        }
    }
}
