//@GeneratedCode
namespace QTSchool.Logic.Models.App
{
    ///
    /// Generated by the generator
    ///
    public partial class Course
    {
        ///
        /// Generated by the generator
        ///
        static Course()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public Course()
        {
            Constructing();
            _source = new Entities.App.Course();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        internal Course(Entities.App.Course source)
        {
            Constructing();
            _source = source;
            Constructed();
        }
        
        new internal Entities.App.Course Source
        {
            get => (Entities.App.Course)(_source!);
            set => _source = value;
        }
        
        public System.String Designation
        {
            get => Source.Designation;
            set => Source.Designation = value;
        }
        
        public System.String? Description
        {
            get => Source.Description;
            set => Source.Description = value;
        }
        
        public System.Int32 MaxStudents
        {
            get => Source.MaxStudents;
            set => Source.MaxStudents = value;
        }
        
        private CommonBase.Modules.Collection.DelegateList<QTSchool.Logic.Entities.App.Student, QTSchool.Logic.Models.App.Student>? _students;
        public System.Collections.Generic.IList<QTSchool.Logic.Models.App.Student> Students
        {
            get => _students ??= new CommonBase.Modules.Collection.DelegateList<QTSchool.Logic.Entities.App.Student, QTSchool.Logic.Models.App.Student>(Source.Students, e => QTSchool.Logic.Models.App.Student.Create(e));
        }
        ///
        /// Generated by the generator
        ///
        internal void CopyProperties(Entities.App.Course other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                Id = other.Id;
                Designation = other.Designation;
                Description = other.Description;
                MaxStudents = other.MaxStudents;
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(Entities.App.Course other, ref bool handled);
        partial void AfterCopyProperties(Entities.App.Course other);
        ///
        /// Generated by the generator
        ///
        public void CopyProperties(QTSchool.Logic.Models.App.Course other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                Id = other.Id;
                Designation = other.Designation;
                Description = other.Description;
                MaxStudents = other.MaxStudents;
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(QTSchool.Logic.Models.App.Course other, ref bool handled);
        partial void AfterCopyProperties(QTSchool.Logic.Models.App.Course other);
        ///
        /// Generated by the generator
        ///
        public override bool Equals(object? obj)
        {
            bool result = false;
            if (obj is Models.App.Course other)
            {
                result = Id == other.Id;
            }
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public override int GetHashCode()
        {
            return this.CalculateHashCode(Id, Designation, Description, MaxStudents, Students);
        }
        ///
        /// Generated by the generator
        ///
        public static QTSchool.Logic.Models.App.Course Create()
        {
            BeforeCreate();
            var result = new QTSchool.Logic.Models.App.Course();
            AfterCreate(result);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static QTSchool.Logic.Models.App.Course Create(object other)
        {
            BeforeCreate(other);
            var result = new QTSchool.Logic.Models.App.Course();
            CommonBase.Extensions.ObjectExtensions.CopyFrom(result, other);
            AfterCreate(result, other);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static QTSchool.Logic.Models.App.Course Create(QTSchool.Logic.Models.App.Course other)
        {
            BeforeCreate(other);
            var result = new QTSchool.Logic.Models.App.Course();
            result.CopyProperties(other);
            AfterCreate(result, other);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static QTSchool.Logic.Models.App.Course Create(Entities.App.Course other)
        {
            BeforeCreate(other);
            var result = new QTSchool.Logic.Models.App.Course();
            result.Source = other;
            AfterCreate(result, other);
            return result;
        }
        static partial void BeforeCreate();
        static partial void AfterCreate(QTSchool.Logic.Models.App.Course instance);
        static partial void BeforeCreate(object other);
        static partial void AfterCreate(QTSchool.Logic.Models.App.Course instance, object other);
        static partial void BeforeCreate(QTSchool.Logic.Models.App.Course other);
        static partial void AfterCreate(QTSchool.Logic.Models.App.Course instance, QTSchool.Logic.Models.App.Course other);
        static partial void BeforeCreate(Entities.App.Course other);
        static partial void AfterCreate(QTSchool.Logic.Models.App.Course instance, Entities.App.Course other);
    }
}
