//@GeneratedCode
namespace QTSchool.Logic.Models.App
{
    ///
    /// Generated by the generator
    ///
    public partial class Student
    {
        ///
        /// Generated by the generator
        ///
        static Student()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public Student()
        {
            Constructing();
            _source = new Entities.App.Student();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        internal Student(Entities.App.Student source)
        {
            Constructing();
            _source = source;
            Constructed();
        }
        
        new internal Entities.App.Student Source
        {
            get => (Entities.App.Student)(_source!);
            set => _source = value;
        }
        
        public System.String FirstName
        {
            get => Source.FirstName;
            set => Source.FirstName = value;
        }
        
        public System.String LastName
        {
            get => Source.LastName;
            set => Source.LastName = value;
        }
        
        public System.DateTime Birthdate
        {
            get => Source.Birthdate;
            set => Source.Birthdate = value;
        }
        
        private CommonBase.Modules.Collection.DelegateList<QTSchool.Logic.Entities.App.Course, QTSchool.Logic.Models.App.Course>? _courses;
        public System.Collections.Generic.IList<QTSchool.Logic.Models.App.Course> Courses
        {
            get => _courses ??= new CommonBase.Modules.Collection.DelegateList<QTSchool.Logic.Entities.App.Course, QTSchool.Logic.Models.App.Course>(Source.Courses, e => QTSchool.Logic.Models.App.Course.Create(e));
        }
        ///
        /// Generated by the generator
        ///
        internal void CopyProperties(Entities.App.Student other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                Id = other.Id;
                FirstName = other.FirstName;
                LastName = other.LastName;
                Birthdate = other.Birthdate;
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(Entities.App.Student other, ref bool handled);
        partial void AfterCopyProperties(Entities.App.Student other);
        ///
        /// Generated by the generator
        ///
        public void CopyProperties(QTSchool.Logic.Models.App.Student other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                Id = other.Id;
                FirstName = other.FirstName;
                LastName = other.LastName;
                Birthdate = other.Birthdate;
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(QTSchool.Logic.Models.App.Student other, ref bool handled);
        partial void AfterCopyProperties(QTSchool.Logic.Models.App.Student other);
        ///
        /// Generated by the generator
        ///
        public override bool Equals(object? obj)
        {
            bool result = false;
            if (obj is Models.App.Student other)
            {
                result = Id == other.Id;
            }
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public override int GetHashCode()
        {
            return this.CalculateHashCode(Id, FirstName, LastName, Birthdate, Courses);
        }
        ///
        /// Generated by the generator
        ///
        public static QTSchool.Logic.Models.App.Student Create()
        {
            BeforeCreate();
            var result = new QTSchool.Logic.Models.App.Student();
            AfterCreate(result);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static QTSchool.Logic.Models.App.Student Create(object other)
        {
            BeforeCreate(other);
            var result = new QTSchool.Logic.Models.App.Student();
            CommonBase.Extensions.ObjectExtensions.CopyFrom(result, other);
            AfterCreate(result, other);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static QTSchool.Logic.Models.App.Student Create(QTSchool.Logic.Models.App.Student other)
        {
            BeforeCreate(other);
            var result = new QTSchool.Logic.Models.App.Student();
            result.CopyProperties(other);
            AfterCreate(result, other);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static QTSchool.Logic.Models.App.Student Create(Entities.App.Student other)
        {
            BeforeCreate(other);
            var result = new QTSchool.Logic.Models.App.Student();
            result.Source = other;
            AfterCreate(result, other);
            return result;
        }
        static partial void BeforeCreate();
        static partial void AfterCreate(QTSchool.Logic.Models.App.Student instance);
        static partial void BeforeCreate(object other);
        static partial void AfterCreate(QTSchool.Logic.Models.App.Student instance, object other);
        static partial void BeforeCreate(QTSchool.Logic.Models.App.Student other);
        static partial void AfterCreate(QTSchool.Logic.Models.App.Student instance, QTSchool.Logic.Models.App.Student other);
        static partial void BeforeCreate(Entities.App.Student other);
        static partial void AfterCreate(QTSchool.Logic.Models.App.Student instance, Entities.App.Student other);
    }
}
