//@GeneratedCode
namespace QTSchool.Logic.Facades.App
{
    using TOutModel = Models.App.Course;
    ///
    /// Generated by the generator
    ///
    public sealed partial class CoursesFacade : ControllerFacade<TOutModel>, Contracts.App.ICoursesAccess
    {
        ///
        /// Generated by the generator
        ///
        static CoursesFacade()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public CoursesFacade()
        : base(new QTSchool.Logic.Controllers.App.CoursesController())
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public CoursesFacade(FacadeObject facadeObject)
        : base(new QTSchool.Logic.Controllers.App.CoursesController(facadeObject.ControllerObject))
        {
            Constructing();
            
            Constructed();
        }
    }
}
