//@GeneratedCode
namespace QTSchool.MvvMApp.Models.App
{
    using System;
    ///
    /// Generated by the generator
    ///
    
    public partial class Course
    {
        ///
        /// Generated by the generator
        ///
        static Course()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public Course()
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        
        public System.String Designation { get; set; } = string.Empty;
        ///
        /// Generated by the generator
        ///
        
        public System.String? Description { get; set; }
        ///
        /// Generated by the generator
        ///
        
        public System.Int32 MaxStudents { get; set; }
        ///
        /// Generated by the generator
        ///
        
        public System.Collections.Generic.List<QTSchool.MvvMApp.Models.App.Student> Students { get; set; } = new();
        ///
        /// Generated by the generator
        ///
        public static QTSchool.MvvMApp.Models.App.Course Create()
        {
            BeforeCreate();
            var result = new QTSchool.MvvMApp.Models.App.Course();
            AfterCreate(result);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static QTSchool.MvvMApp.Models.App.Course Create(object other)
        {
            BeforeCreate(other);
            var result = new QTSchool.MvvMApp.Models.App.Course();
            CommonBase.Extensions.ObjectExtensions.CopyFrom(result, other);
            AfterCreate(result, other);
            return result;
        }
        static partial void BeforeCreate();
        static partial void AfterCreate(QTSchool.MvvMApp.Models.App.Course instance);
        static partial void BeforeCreate(object other);
        static partial void AfterCreate(QTSchool.MvvMApp.Models.App.Course instance, object other);
        ///
        /// Generated by the generator
        ///
        public override bool Equals(object? obj)
        {
            bool result = false;
            if (obj is Models.App.Course other)
            {
                result = Id == other.Id;
            }
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public override int GetHashCode()
        {
            return this.CalculateHashCode(Id, Designation, Description, MaxStudents, Students);
        }
    }
}
