//@GeneratedCode
namespace QTSchool.MvvMApp.Models.App
{
    using System;
    ///
    /// Generated by the generator
    ///
    
    public partial class Student
    {
        ///
        /// Generated by the generator
        ///
        static Student()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public Student()
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        
        public System.String FirstName { get; set; } = string.Empty;
        ///
        /// Generated by the generator
        ///
        
        public System.String LastName { get; set; } = string.Empty;
        ///
        /// Generated by the generator
        ///
        
        public System.DateTime Birthdate { get; set; }
        ///
        /// Generated by the generator
        ///
        
        public System.Collections.Generic.List<QTSchool.MvvMApp.Models.App.Course> Courses { get; set; } = new();
        ///
        /// Generated by the generator
        ///
        public static QTSchool.MvvMApp.Models.App.Student Create()
        {
            BeforeCreate();
            var result = new QTSchool.MvvMApp.Models.App.Student();
            AfterCreate(result);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static QTSchool.MvvMApp.Models.App.Student Create(object other)
        {
            BeforeCreate(other);
            var result = new QTSchool.MvvMApp.Models.App.Student();
            CommonBase.Extensions.ObjectExtensions.CopyFrom(result, other);
            AfterCreate(result, other);
            return result;
        }
        static partial void BeforeCreate();
        static partial void AfterCreate(QTSchool.MvvMApp.Models.App.Student instance);
        static partial void BeforeCreate(object other);
        static partial void AfterCreate(QTSchool.MvvMApp.Models.App.Student instance, object other);
        ///
        /// Generated by the generator
        ///
        public override bool Equals(object? obj)
        {
            bool result = false;
            if (obj is Models.App.Student other)
            {
                result = Id == other.Id;
            }
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public override int GetHashCode()
        {
            return this.CalculateHashCode(Id, FirstName, LastName, Birthdate, Courses);
        }
    }
}
