//@GeneratedCode
namespace QTSchool.WebApi.Models.App
{
    using System;
    ///
    /// Generated by the generator
    ///
    public partial class CourseEdit
    {
        ///
        /// Generated by the generator
        ///
        static CourseEdit()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public CourseEdit()
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public System.String Designation { get; set; } = string.Empty;
        ///
        /// Generated by the generator
        ///
        public System.String? Description { get; set; }
        ///
        /// Generated by the generator
        ///
        public System.Int32 MaxStudents { get; set; }
    }
}
