//@GeneratedCode
namespace QTSchool.WebApi.Models.App
{
    using System;
    ///
    /// Generated by the generator
    ///
    
    public partial class Course
    {
        ///
        /// Generated by the generator
        ///
        static Course()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public Course()
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        
        public System.String Designation { get; set; } = string.Empty;
        ///
        /// Generated by the generator
        ///
        
        public System.String? Description { get; set; }
        ///
        /// Generated by the generator
        ///
        
        public System.Int32 MaxStudents { get; set; }
        ///
        /// Generated by the generator
        ///
        
        public System.Collections.Generic.List<QTSchool.WebApi.Models.App.Student> Students { get; set; } = new();
        ///
        /// Generated by the generator
        ///
        public static QTSchool.WebApi.Models.App.Course Create()
        {
            BeforeCreate();
            var result = new QTSchool.WebApi.Models.App.Course();
            AfterCreate(result);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static QTSchool.WebApi.Models.App.Course Create(object other)
        {
            BeforeCreate(other);
            var result = new QTSchool.WebApi.Models.App.Course();
            CommonBase.Extensions.ObjectExtensions.CopyFrom(result, other);
            AfterCreate(result, other);
            return result;
        }
        static partial void BeforeCreate();
        static partial void AfterCreate(QTSchool.WebApi.Models.App.Course instance);
        static partial void BeforeCreate(object other);
        static partial void AfterCreate(QTSchool.WebApi.Models.App.Course instance, object other);
        ///
        /// Generated by the generator
        ///
        public static QTSchool.WebApi.Models.App.Course Create(QTSchool.Logic.Models.App.Course other)
        {
            BeforeCreate(other);
            var result = new QTSchool.WebApi.Models.App.Course();
            result.CopyProperties(other);
            AfterCreate(result, other);
            return result;
        }
        static partial void BeforeCreate(QTSchool.Logic.Models.App.Course other);
        static partial void AfterCreate(QTSchool.WebApi.Models.App.Course instance, QTSchool.Logic.Models.App.Course other);
        ///
        /// Generated by the generator
        ///
        public void CopyProperties(QTSchool.Logic.Models.App.Course other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                Id = other.Id;
                Designation = other.Designation;
                Description = other.Description;
                MaxStudents = other.MaxStudents;
                Students = other.Students.Select(e => QTSchool.WebApi.Models.App.Student.Create((object)e)).ToList();
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(QTSchool.Logic.Models.App.Course other, ref bool handled);
        partial void AfterCopyProperties(QTSchool.Logic.Models.App.Course other);
        ///
        /// Generated by the generator
        ///
        public void CopyProperties(QTSchool.WebApi.Models.App.Course other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                Id = other.Id;
                Designation = other.Designation;
                Description = other.Description;
                MaxStudents = other.MaxStudents;
                Students = other.Students.Select(e => QTSchool.WebApi.Models.App.Student.Create((object)e)).ToList();
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(QTSchool.WebApi.Models.App.Course other, ref bool handled);
        partial void AfterCopyProperties(QTSchool.WebApi.Models.App.Course other);
        ///
        /// Generated by the generator
        ///
        public override bool Equals(object? obj)
        {
            bool result = false;
            if (obj is Models.App.Course other)
            {
                result = Id == other.Id;
            }
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public override int GetHashCode()
        {
            return this.CalculateHashCode(Id, Designation, Description, MaxStudents, Students);
        }
    }
}
