//@GeneratedCode
namespace QTSchool.WebApi.Models.App
{
    using System;
    ///
    /// Generated by the generator
    ///
    public partial class StudentEdit
    {
        ///
        /// Generated by the generator
        ///
        static StudentEdit()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public StudentEdit()
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public System.String FirstName { get; set; } = string.Empty;
        ///
        /// Generated by the generator
        ///
        public System.String LastName { get; set; } = string.Empty;
        ///
        /// Generated by the generator
        ///
        public System.DateTime Birthdate { get; set; }
    }
}
