//@GeneratedCode
namespace QTSchool.WebApi.Models.App
{
    using System;
    ///
    /// Generated by the generator
    ///
    
    public partial class Student
    {
        ///
        /// Generated by the generator
        ///
        static Student()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public Student()
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        
        public System.String FirstName { get; set; } = string.Empty;
        ///
        /// Generated by the generator
        ///
        
        public System.String LastName { get; set; } = string.Empty;
        ///
        /// Generated by the generator
        ///
        
        public System.DateTime Birthdate { get; set; }
        ///
        /// Generated by the generator
        ///
        
        public System.Collections.Generic.List<QTSchool.WebApi.Models.App.Course> Courses { get; set; } = new();
        ///
        /// Generated by the generator
        ///
        public static QTSchool.WebApi.Models.App.Student Create()
        {
            BeforeCreate();
            var result = new QTSchool.WebApi.Models.App.Student();
            AfterCreate(result);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static QTSchool.WebApi.Models.App.Student Create(object other)
        {
            BeforeCreate(other);
            var result = new QTSchool.WebApi.Models.App.Student();
            CommonBase.Extensions.ObjectExtensions.CopyFrom(result, other);
            AfterCreate(result, other);
            return result;
        }
        static partial void BeforeCreate();
        static partial void AfterCreate(QTSchool.WebApi.Models.App.Student instance);
        static partial void BeforeCreate(object other);
        static partial void AfterCreate(QTSchool.WebApi.Models.App.Student instance, object other);
        ///
        /// Generated by the generator
        ///
        public static QTSchool.WebApi.Models.App.Student Create(QTSchool.Logic.Models.App.Student other)
        {
            BeforeCreate(other);
            var result = new QTSchool.WebApi.Models.App.Student();
            result.CopyProperties(other);
            AfterCreate(result, other);
            return result;
        }
        static partial void BeforeCreate(QTSchool.Logic.Models.App.Student other);
        static partial void AfterCreate(QTSchool.WebApi.Models.App.Student instance, QTSchool.Logic.Models.App.Student other);
        ///
        /// Generated by the generator
        ///
        public void CopyProperties(QTSchool.Logic.Models.App.Student other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                Id = other.Id;
                FirstName = other.FirstName;
                LastName = other.LastName;
                Birthdate = other.Birthdate;
                Courses = other.Courses.Select(e => QTSchool.WebApi.Models.App.Course.Create((object)e)).ToList();
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(QTSchool.Logic.Models.App.Student other, ref bool handled);
        partial void AfterCopyProperties(QTSchool.Logic.Models.App.Student other);
        ///
        /// Generated by the generator
        ///
        public void CopyProperties(QTSchool.WebApi.Models.App.Student other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                Id = other.Id;
                FirstName = other.FirstName;
                LastName = other.LastName;
                Birthdate = other.Birthdate;
                Courses = other.Courses.Select(e => QTSchool.WebApi.Models.App.Course.Create((object)e)).ToList();
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(QTSchool.WebApi.Models.App.Student other, ref bool handled);
        partial void AfterCopyProperties(QTSchool.WebApi.Models.App.Student other);
        ///
        /// Generated by the generator
        ///
        public override bool Equals(object? obj)
        {
            bool result = false;
            if (obj is Models.App.Student other)
            {
                result = Id == other.Id;
            }
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public override int GetHashCode()
        {
            return this.CalculateHashCode(Id, FirstName, LastName, Birthdate, Courses);
        }
    }
}
