//@GeneratedCode
namespace QTSchool.Logic.Contracts.App
{
    using TOutModel = Models.App.Course;
    ///
    /// Generated by the generator
    ///
    public partial interface ICoursesAccess : Contracts.IDataAccess<TOutModel>
    {

    }
}
