//@GeneratedCode
namespace QTSchool.Logic.Contracts.App
{
    using TOutModel = Models.App.Student;
    ///
    /// Generated by the generator
    ///
    public partial interface IStudentsAccess : Contracts.IDataAccess<TOutModel>
    {
    }
}
